CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "age" int,
  "course_id" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "level" varchar NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar,
  "course_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" int,
  "id_course" int,
  "id_categorie" int
);


insert into categories (


name



)

values('Bases de datos');


insert into categories(

name

)

values('Desarrollo Backend');

insert into categories (


name



)

values('Desarrollo Frontend');


insert into categories(

name

)

values('Desarrollo Full-Stack');

ALTER TABLE "users" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("id_categorie") REFERENCES "categories" ("id");


insert into users (
first_name,
last_name,
email,
"password",
phone,
age)

values (

'Adrian',
'Perez',
'adrian@gmail.com',
'root',
'3678903456',
23

);

insert into users (
first_name,
last_name,
email,
"password",
phone,
age)

values (

'Camila',
'Rodrigez',
'camila@gmail.com',
'cami22',
'3135678989',
22

);

insert into courses (

title,
description,
"level",
teacher


)

values (

'HTML',
'HyperText Markup Language',
'Principiante',
'Armando Castro'


);

insert into courses (

title,
description,
"level",
teacher


)

values (

'CSS',
'Cascade StyleSheet',
'Principiante',
'Rodrigo Torres'


);

insert into course_videos (

title,
url,
course_id


)

values(

'Primer Video de HTML',
'https://www.html-basico.com',
1

);

insert into course_videos (

title,
url,
course_id


)

values(

'Primer Video de CSS',
'https://www.css-basico.com',
2

);








































